version: '3.8'

services:
  # Node.js application service
  app:
    build: .
    ports:
      - "3000:3000"  # Expose the app on port 3000
    environment:
      MYSQL_HOST: db  # Reference to the MySQL container
      MYSQL_USER: root  # MySQL username
      MYSQL_PASSWORD: root  # MySQL password
      MYSQL_DATABASE: blood_donation  # Database name
    depends_on:
      - db  # Ensure the database container starts first
    networks:
      - app-network

  # MySQL database service
  db:
    image: mysql:5.7  # Use MySQL version 5.7
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set the root password
      MYSQL_DATABASE: blood_donation  # Create the database
    volumes:
      - db_data:/var/lib/mysql  # Persistent data storage
      - ./Schema.sql:/docker-entrypoint-initdb.d/Schema.sql  # Mount Schema.sql to initialize database
    ports:
      - "3306:3306"  # Expose MySQL port
    networks:
      - app-network

# Define a volume to persist MySQL data
volumes:
  db_data:

# Define the network to connect the containers
networks:
  app-network:
    driver: bridge
